"""add_allocation_percentage_to_invoices

Revision ID: 1ce5a9379a8f
Revises: 33258adef341
Create Date: 2025-12-22 14:20:46.795247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ce5a9379a8f'
down_revision: Union[str, None] = '33258adef341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('allocation_percentage', sa.Numeric(precision=5, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'allocation_percentage')
    # ### end Alembic commands ###
