"""add_include_in_export_to_documents

Revision ID: 33258adef341
Revises: 94d820c60eb1
Create Date: 2025-12-22 13:41:47.261234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33258adef341'
down_revision: Union[str, None] = '94d820c60eb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('include_in_export', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'include_in_export')
    # ### end Alembic commands ###
