"""add_settings_table

Revision ID: 93d1a0107f1c
Revises: 1ce5a9379a8f
Create Date: 2025-12-22 17:21:10.181651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93d1a0107f1c'
down_revision: Union[str, None] = '1ce5a9379a8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
