"""initial

Revision ID: 94d820c60eb1
Revises: 
Create Date: 2025-12-22 12:24:52.786529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94d820c60eb1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('street', sa.String(length=255), nullable=False),
    sa.Column('house_number', sa.String(length=20), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('total_area_sqm', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settlements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CALCULATED', 'FINALIZED', 'EXPORTED', name='settlementstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('designation', sa.String(length=50), nullable=False),
    sa.Column('area_sqm', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('rooms', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('has_balcony', sa.Boolean(), nullable=False),
    sa.Column('has_garden', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('settlement_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('document_status', sa.Enum('PENDING', 'PROCESSING', 'PROCESSED', 'FAILED', 'VERIFIED', name='documentstatus'), nullable=False),
    sa.Column('ocr_raw_text', sa.Text(), nullable=True),
    sa.Column('ocr_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('upload_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manual_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('settlement_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=True),
    sa.Column('entry_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost_category', sa.Enum('GRUNDSTEUER', 'WASSERVERSORGUNG', 'ENTWAESSERUNG', 'HEIZUNG', 'WARMWASSER', 'VERBUNDENE_ANLAGEN', 'AUFZUG', 'STRASSENREINIGUNG', 'GEBAEUDEREINIGUNG', 'GARTENPFLEGE', 'BELEUCHTUNG', 'SCHORNSTEINREINIGUNG', 'VERSICHERUNG', 'HAUSWART', 'ANTENNE_KABEL', 'WAESCHEPFLEGE', 'SONSTIGE', name='costcategory'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('salutation', sa.String(length=20), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('move_in_date', sa.Date(), nullable=False),
    sa.Column('move_out_date', sa.Date(), nullable=True),
    sa.Column('resident_count', sa.Integer(), nullable=False),
    sa.Column('monthly_prepayment', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit_allocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('cost_category', sa.Enum('GRUNDSTEUER', 'WASSERVERSORGUNG', 'ENTWAESSERUNG', 'HEIZUNG', 'WARMWASSER', 'VERBUNDENE_ANLAGEN', 'AUFZUG', 'STRASSENREINIGUNG', 'GEBAEUDEREINIGUNG', 'GARTENPFLEGE', 'BELEUCHTUNG', 'SCHORNSTEINREINIGUNG', 'VERSICHERUNG', 'HAUSWART', 'ANTENNE_KABEL', 'WAESCHEPFLEGE', 'SONSTIGE', name='costcategory'), nullable=False),
    sa.Column('allocation_method', sa.Enum('WOHNFLAECHE', 'PERSONENZAHL', 'EINHEIT', 'VERBRAUCH', 'MITEIGENTUMSANTEIL', name='allocationmethod'), nullable=False),
    sa.Column('allocation_percentage', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('custom_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id', 'cost_category', name='uq_unit_cost_category')
    )
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('settlement_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('vendor_name', sa.String(length=255), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost_category', sa.Enum('GRUNDSTEUER', 'WASSERVERSORGUNG', 'ENTWAESSERUNG', 'HEIZUNG', 'WARMWASSER', 'VERBUNDENE_ANLAGEN', 'AUFZUG', 'STRASSENREINIGUNG', 'GEBAEUDEREINIGUNG', 'GARTENPFLEGE', 'BELEUCHTUNG', 'SCHORNSTEINREINIGUNG', 'VERSICHERUNG', 'HAUSWART', 'ANTENNE_KABEL', 'WAESCHEPFLEGE', 'SONSTIGE', name='costcategory'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settlement_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('settlement_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('total_costs', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_prepayments', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('occupancy_days', sa.Integer(), nullable=False),
    sa.Column('calculation_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('settlement_id', 'unit_id', 'tenant_id', name='uq_settlement_unit_tenant')
    )
    op.create_table('tenant_addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('street', sa.String(length=255), nullable=False),
    sa.Column('house_number', sa.String(length=20), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('line_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cost_category', sa.Enum('GRUNDSTEUER', 'WASSERVERSORGUNG', 'ENTWAESSERUNG', 'HEIZUNG', 'WARMWASSER', 'VERBUNDENE_ANLAGEN', 'AUFZUG', 'STRASSENREINIGUNG', 'GEBAEUDEREINIGUNG', 'GARTENPFLEGE', 'BELEUCHTUNG', 'SCHORNSTEINREINIGUNG', 'VERSICHERUNG', 'HAUSWART', 'ANTENNE_KABEL', 'WAESCHEPFLEGE', 'SONSTIGE', name='costcategory'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settlement_cost_breakdowns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('settlement_result_id', sa.UUID(), nullable=False),
    sa.Column('cost_category', sa.Enum('GRUNDSTEUER', 'WASSERVERSORGUNG', 'ENTWAESSERUNG', 'HEIZUNG', 'WARMWASSER', 'VERBUNDENE_ANLAGEN', 'AUFZUG', 'STRASSENREINIGUNG', 'GEBAEUDEREINIGUNG', 'GARTENPFLEGE', 'BELEUCHTUNG', 'SCHORNSTEINREINIGUNG', 'VERSICHERUNG', 'HAUSWART', 'ANTENNE_KABEL', 'WAESCHEPFLEGE', 'SONSTIGE', name='costcategory'), nullable=False),
    sa.Column('total_property_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('allocation_percentage', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('allocation_method', sa.Enum('WOHNFLAECHE', 'PERSONENZAHL', 'EINHEIT', 'VERBRAUCH', 'MITEIGENTUMSANTEIL', name='allocationmethod'), nullable=False),
    sa.ForeignKeyConstraint(['settlement_result_id'], ['settlement_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('settlement_result_id', 'cost_category', name='uq_result_category')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settlement_cost_breakdowns')
    op.drop_table('line_items')
    op.drop_table('tenant_addresses')
    op.drop_table('settlement_results')
    op.drop_table('invoices')
    op.drop_table('unit_allocations')
    op.drop_table('tenants')
    op.drop_table('manual_entries')
    op.drop_table('documents')
    op.drop_table('units')
    op.drop_table('settlements')
    op.drop_table('properties')
    # ### end Alembic commands ###
